server.port=8080
jira.baseUrl=https://jira.thy.com
jira.personalAccessToken=${JIRA_TOKEN}
jira.apiSearchPath=/rest/api/2/search
jira.maxResults=100

# Logging - token loglarda gorunmesin
logging.level.com.thy.audithub=INFO

# Encoding - Turkce karakter destegi
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.mandatory-file-encoding=UTF-8